// Generates src/assets/og-card.svg, the source of public/og.png, from the
// logo of the site's default theme (DEFAULT_THEME in src/themes.mjs, BLUESHIFT:
// public/logo/nu11signal-blueshift.svg), so the card can never drift from the
// logo, and copies the default theme's mark to public/favicon.svg. The logo's <defs> and
// artwork are copied in, scaled to 1020px wide and centered on a 1200x630
// card with the BLUESHIFT ink, a soft blue glow, scanlines and a thin frame
// in the theme's dim blue (the colors of global.css :root, BLUESHIFT).
//
// Usage: node tools/og-card.mjs   (npm run brand runs it, then rsvg-convert)
//        tools/check-brand.mjs imports renderOgCard() and the paths below to
//        detect drift.

import { copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { logoFile } from '../src/themes.mjs';

const path = (rel) => fileURLToPath(new URL(`../${rel}`, import.meta.url));

/** The default theme's logo and mark, as paths relative to the repository. */
export const LOGO_REL = `public/${logoFile('logo')}`;
export const MARK_REL = `public/${logoFile('mark')}`;
export const LOGO = path(LOGO_REL);
export const MARK = path(MARK_REL);
export const CARD = path('src/assets/og-card.svg');
export const FAVICON = path('public/favicon.svg');

const W = 1200;
const H = 630;
const LOGO_W = 1020;

// BLUESHIFT colors (global.css :root): ink, primary blue, frame (dim).
const INK = '#05070F';
const GLOW = '#347AFF';
const FRAME = '#1C2C54';

// Returns the og-card SVG text for the given logo SVG text.
export function renderOgCard(logo) {
  const open = logo.match(/<svg\b[^>]*>/);
  const viewBox = open?.[0].match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  const end = logo.lastIndexOf('</svg>');
  if (!open || !viewBox || end < 0) throw new Error('og-card: logo SVG has no <svg viewBox="0 0 w h"> root');

  // The logo's children minus its title, desc and metadata: <defs> + artwork.
  const body = logo
    .slice(open.index + open[0].length, end)
    .replace(/<(title|desc|metadata)\b[^>]*>[\s\S]*?<\/\1>/g, '')
    .split('\n')
    .filter((line) => line.trim() !== '')
    .join('\n');
  if (!body.includes('<defs>')) throw new Error('og-card: logo SVG has no <defs>');

  const [vw, vh] = [Number(viewBox[1]), Number(viewBox[2])];
  const scale = LOGO_W / vw;
  const x = (W - LOGO_W) / 2;
  const y = (H - vh * scale) / 2;

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/og-card.mjs from ${LOGO_REL};
     do not edit. Source of public/og.png (1200x630): npm run brand -->
<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
<defs>
<radialGradient id="og-glow" cx="50%" cy="50%" r="60%"><stop offset="0" stop-color="${GLOW}" stop-opacity="0.18"/><stop offset="1" stop-color="${GLOW}" stop-opacity="0"/></radialGradient>
<pattern id="og-scan" width="4" height="4" patternUnits="userSpaceOnUse"><rect width="4" height="1" fill="#FFFFFF" fill-opacity="0.025"/></pattern>
</defs>
<rect width="${W}" height="${H}" fill="${INK}"/>
<rect width="${W}" height="${H}" fill="url(#og-glow)"/>
<rect width="${W}" height="${H}" fill="url(#og-scan)"/>
<rect x="24" y="24" width="${W - 48}" height="${H - 48}" fill="none" stroke="${FRAME}" stroke-width="2"/>
<g transform="translate(${x.toFixed(2)},${y.toFixed(2)}) scale(${scale.toFixed(6)})">
${body}
</g>
</svg>
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(CARD, renderOgCard(readFileSync(LOGO, 'utf8')));
  console.log(`og-card: wrote src/assets/og-card.svg from ${LOGO_REL}`);
  copyFileSync(MARK, FAVICON);
  console.log(`og-card: copied ${MARK_REL} to public/favicon.svg`);
}
